image: "registry.sensetime.com/xlab/sensestar-docker:cuda92-centos7-hpc"
# image: "registry.sensetime.com/spring/spring-devel:v0.2.0_cuda9.0_20201116"


variables:
  CI: "true"

stages:
  - build

build:
  stage: build
  script:
    - ls /usr/include/python3.6m/Python.h
    - pip install setuptools==42.0.2 wheel==0.33.6
    - python setup.py bdist_wheel upload -r http://10.198.8.31:23290
  tags:
    - p4
  only:
    - master
    - build-dev

