image: "registry.sensetime.com/xlab/sensestar-docker:cuda92-centos7"

variables:
  CI: "true"

stages:
  - build

build:
  stage: build
  script:
    - export TORCH_CUDA_ARCH_LIST=“7.5”
    - pip install setuptools wheel
    - python setup.py bdist_wheel upload -r http://10.198.8.31:23290
  only:
    - master
    - build-dev

