image: "registry.sensetime.com/xlab/sensestar-docker:cuda92-centos7-hpc"
# image: "registry.sensetime.com/xlab/sensestar-docker:cuda92-centos7-hpc-py37"

variables:
  CI: "true"

stages:
  - build

build:
  stage: build
  script:
    - gcc --version
    - pip install setuptools==42.0.2 wheel==0.33.6
    - python3 setup.py bdist_wheel upload -r http://10.198.8.31:23290
  tags:
    - p4
  only:
    - master
    - build-dev

